CREATE DATABASE pd_kelmin_miranda_tayrona;

CREATE TABLE states (
id_status INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE banks (
id_bank INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE transaction_types (
id_type_transaction INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE clients (
id_client INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
identification VARCHAR(20) NOT NULL UNIQUE,
address VARCHAR(255) NOT NULL,
phone_number VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE bills (
id_bill INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
num_bill VARCHAR(10) NOT NULL UNIQUE,
bill_period DATE NOT NULL,
invoiced_amount DECIMAL(18,4) NOT NULL,
amount_paid DECIMAL(18,4),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
id_transaction INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
client_id INT,
bill_id INT,
status_id INT,
transaction_type_id INT,
bank_id INT,
code VARCHAR(20),
transaction_amount DECIMAL(18,4) NOT NULL,
date_time DATETIME NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY (client_id) REFERENCES clients (id_client) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (bill_id) REFERENCES bills (id_bill) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (status_id) REFERENCES states (id_status) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (transaction_type_id) REFERENCES transaction_types (id_type_transaction) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (bank_id) REFERENCES banks (id_bank) ON DELETE SET NULL ON UPDATE CASCADE
);